import{a as m,S as d,i as c}from"./assets/vendor-BGqwtSVv.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();const g="56464018-9d065431ef651fdc70593a5c2",h="https://pixabay.com/api/";function y(s){const t={key:g,q:s,image_type:"photo",orientation:"horizontal",safesearch:"true"};return m.get(h,{params:t}).then(o=>o.data)}const l=document.querySelector(".gallery"),a=document.querySelector(".loader"),b=new d(".gallery a",{captionsData:"alt",captionDelay:250});function L(s){const t=s.map(({webformatURL:o,largeImageURL:n,tags:e,likes:r,views:i,comments:p,downloads:f})=>`<li class="gallery-item">
        <a class="gallery-link" href="${n}">
          <img class="gallery-image" src="${o}" alt="${e}" />
        </a>
        <div class="info-container">
          <p class="info-item"><b>Likes</b> <span>${r}</span></p>
          <p class="info-item"><b>Views</b> <span>${i}</span></p>
          <p class="info-item"><b>Comments</b> <span>${p}</span></p>
          <p class="info-item"><b>Downloads</b> <span>${f}</span></p>
        </div>
      </li>`).join("");l.innerHTML=t,b.refresh()}function F(){l.innerHTML=""}function S(){a&&a.classList.remove("is-hidden")}function P(){a&&a.classList.add("is-hidden")}const u=document.querySelector(".form");u.addEventListener("submit",q);function q(s){s.preventDefault();const t=s.currentTarget.elements["search-text"].value.trim();if(t===""){c.warning({title:"Warning",message:"Please enter a search query",position:"topRight"});return}F(),S(),y(t).then(o=>{if(o.hits.length===0){c.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",messageColor:"#FFF",backgroundColor:"#EF4040",closeColor:"#FFF",icon:"ico-error",iconColor:"#FFF"});return}L(o.hits)}).catch(o=>{c.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"}),console.error(o)}).finally(()=>{P(),u.reset()})}
//# sourceMappingURL=index.js.map
